### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [antropovaa/PianoTiles#1]
1. В программе не должно быть абсолютных путей
https://github.com/antropovaa/PianoTiles/blob/1790efc4e75777a6a6e0f52cbae4c90fa0972d3e/src/sample/Piano.java#L30
Попробуйте разобраться с механизмом ресурсов.
2. Пока не избавились от повторного проигрывания звука при нажатии клавиши
3. Говорят, что чтобы что-то сыграть хорошо бы иметь на экране сразу две октавы (но я сам не в курсе)

**Comment by antropovaa** [comment]
Насчет 2 пункта:
я пыталась исправить эту проблему, как мы и обсуждали, добавив флаг, который отображал бы нажата кнопка или нет, в итоге теперь нельзя одновременно нажать две кнопки с клавиатуры. Так что сейчас думаю над другим способом, либо можно попытаться усовершенствовать способ с флагом, чтобы он применялся к конкретной клавише, а не к событию в целом.

**Comment by antropovaa** [comment]
Исправила ошибки, за исключением добавления второй октавы на экран, хочу пока улучшить то,  что уже есть

**Comment by gagarski** [comment]
👍

**Comment by antropovaa** [comment]
Добавила вторую октаву и в целом улучшила внешний вид. Считаю задание выполненным
